# Generated by Django 2.0.2 on 2018-02-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
