# Generated by Django 2.0.2 on 2018-02-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iws', '0002_auto_20180204_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iws.Field', unique=True),
        ),
    ]
